// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTaskResponse = "task_response"

// TaskResponse mapped from table <task_response>
type TaskResponse struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:默认主键" json:"id"`
	Rid        string `gorm:"column:rid;not null;comment:日志uuidv4主键" json:"rid"`
	TaskID     string `gorm:"column:task_id;not null;comment:任务id主键" json:"task_id"`
	ProjectID  int64  `gorm:"column:project_id;not null;comment:项目id" json:"project_id"`
	Vid        int64  `gorm:"column:vid;not null;comment:项目版本主键" json:"vid"`
	ExecAt     int64  `gorm:"column:exec_at;not null;comment:执行时间" json:"exec_at"`
	ExecType   int64  `gorm:"column:exec_type;not null;comment:执行类型:-1不执行 0定时执行 1立即执行" json:"exec_type"`
	TaskStatus int64  `gorm:"column:task_status;not null;comment:任务状态: 1成功 -1失败" json:"task_status"`
	Report     string `gorm:"column:report" json:"report"`
	CreatedAt  int64  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`
	UpdatedAt  int64  `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`
}

// TableName TaskResponse's table name
func (*TaskResponse) TableName() string {
	return TableNameTaskResponse
}
