// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTeam = "team"

// Team mapped from table <team>
type Team struct {
	TeamID            int64  `gorm:"column:team_id;primaryKey;autoIncrement:true;comment:ID" json:"team_id"`
	LocalTeamID       string `gorm:"column:local_team_id;not null;comment:本地保存的项目id" json:"local_team_id"`
	Name              string `gorm:"column:name;not null;comment:团队名称" json:"name"`
	Logo              string `gorm:"column:logo;not null;comment:logo" json:"logo"`
	Intro             string `gorm:"column:intro;not null;comment:团队介绍" json:"intro"`
	UserID            int64  `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`
	IsDefault         int64  `gorm:"column:is_default;not null;comment:是否为用户默认(私有)团队 0-否 1-是" json:"is_default"`
	CreateDtime       int64  `gorm:"column:create_dtime;not null;comment:创建时间" json:"create_dtime"`
	InvitecodeUpgrade int64  `gorm:"column:invitecode_upgrade;default:-1" json:"invitecode_upgrade"`
	FeeExpireDtime    int64  `gorm:"column:fee_expire_dtime;not null;comment:是否为免费 0-免费 非0为付费到期日期" json:"fee_expire_dtime"`
	Status            int64  `gorm:"column:status;not null;default:1;comment:状态 1-正常 -1已解散" json:"status"`
	ScoreUpgrade      int64  `gorm:"column:score_upgrade" json:"score_upgrade"`
	UpdatedAt         int64  `gorm:"column:updated_at;not null" json:"updated_at"`
	UpdatedID         int64  `gorm:"column:updated_id;not null;comment:更新用户ID" json:"updated_id"`
	DeletedAt         int64  `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`
	DeletedID         int64  `gorm:"column:deleted_id;comment:删除人用户ID" json:"deleted_id"`
}

// TableName Team's table name
func (*Team) TableName() string {
	return TableNameTeam
}
