// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTeamPlace = "team_place"

// TeamPlace mapped from table <team_place>
type TeamPlace struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`
	TeamID        int64     `gorm:"column:team_id;not null;comment:团队ID" json:"team_id"`
	UserID        int64     `gorm:"column:user_id;not null;comment:绑定的用户ID" json:"user_id"`
	IsAdmin       int64     `gorm:"column:is_admin;not null;default:-1;comment:是否为管理员 1-是" json:"is_admin"`
	BindDtime     int64     `gorm:"column:bind_dtime;not null;comment:团队成员绑定时间" json:"bind_dtime"`
	IsPresent     int64     `gorm:"column:is_present;not null;default:-1;comment:是否为付费工位 -1-是 1-否" json:"is_present"`
	Status        int64     `gorm:"column:status;not null;default:1;comment:状态 1-正常" json:"status"`
	IsReadonly    int64     `gorm:"column:is_readonly;not null;default:1;comment:工位读写权限 1-读写 2-只读" json:"is_readonly"`
	IsSuperAdmin  int64     `gorm:"column:is_super_admin;not null;default:-1;comment:是否为超级管理员，1是，-1否" json:"is_super_admin"`
	InviterUserID int64     `gorm:"column:inviter_user_id;not null;comment:邀请人" json:"inviter_user_id"`
	ExpiryTime    int64     `gorm:"column:expiry_time;not null;default:4294967295;comment:过期时间" json:"expiry_time"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`
}

// TableName TeamPlace's table name
func (*TeamPlace) TableName() string {
	return TableNameTeamPlace
}
