// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UserID        int64  `gorm:"column:user_id;primaryKey;autoIncrement:true;comment:ID" json:"user_id"`
	Portrait      string `gorm:"column:portrait;not null;comment:头像" json:"portrait"`
	NickName      string `gorm:"column:nick_name;not null;comment:昵称" json:"nick_name"`
	Email         string `gorm:"column:email;comment:邮箱" json:"email"`
	EmailVerify   int64  `gorm:"column:email_verify;default:-1;comment:邮箱验证" json:"email_verify"`
	Mobile        string `gorm:"column:mobile;not null;comment:手机号" json:"mobile"`
	Password      string `gorm:"column:password;comment:密码" json:"password"`
	Salt          string `gorm:"column:salt;not null;comment:密码随机盐" json:"salt"`
	Openid        string `gorm:"column:openid;comment:Openid" json:"openid"`
	WxUnionid     string `gorm:"column:wx_unionid;comment:微信unionid" json:"wx_unionid"`
	AccessToken   string `gorm:"column:access_token;comment:access_token" json:"access_token"`
	RegDtime      int64  `gorm:"column:reg_dtime;comment:注册时间" json:"reg_dtime"`
	LoginDtime    int64  `gorm:"column:login_dtime;comment:登录时间" json:"login_dtime"`
	Score         int64  `gorm:"column:score;comment:积分" json:"score"`
	InviterCode   string `gorm:"column:inviter_code" json:"inviter_code"`
	InviterUserID int64  `gorm:"column:inviter_user_id;not null" json:"inviter_user_id"`
	Status        int64  `gorm:"column:status;default:1;comment:状态 1-正常" json:"status"`
	IsAdmin       int64  `gorm:"column:is_admin;not null;default:-1;comment:是否企业超管 -1-否  1-是" json:"is_admin"`
	MachineID     string `gorm:"column:machineID;comment:设备ID" json:"machineID"`
	InviterSource int64  `gorm:"column:inviter_source;not null;comment:邀请来源 0无邀请人 1url 2email" json:"inviter_source"`
	ChEmailCount  int64  `gorm:"column:ch_email_count;not null;default:2;comment:邮箱修改次数" json:"ch_email_count"`
	RegIP         string `gorm:"column:reg_ip;comment:客户注册时ip地址" json:"reg_ip"`
	RegSource     int64  `gorm:"column:reg_source;not null;comment:院校注册来源" json:"reg_source"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
